package constants

// AllowedOrigins ...
const AllowedOrigins = "ALLOWED_ORIGINS"

// Environment ...
const Environment = "ENVIRONMENT"

// HerokuPort ...
const HerokuPort = "PORT"

// RooseveltPort ...
const RooseveltPort = "ROOSEVELT_PORT"

// RooseveltAddress ...
const RooseveltAddress = "ROOSEVELT_ADDRESS"

// RooseveltWriteTimeout ...
const RooseveltWriteTimeout = "ROOSEVELT_WRITE_TIMEOUT"

// RooseveltReadTimeout ...
const RooseveltReadTimeout = "ROOSEVELT_READ_TIMEOUT"

// RooseveltIdleTimeout ...
const RooseveltIdleTimeout = "ROOSEVELT_IDLE_TIMEOUT"
